site_name: A Considered Approach to Technical Interviews
repo_url: https://github.com/class-act-org/class-act-org.github.io
site_url: https://class-act-org.github.io/

theme:
  name: null
  custom_dir: "cinder"

  features:
    - content.footnote.tooltips

nav:
  - Home: index.md
  - As a Stakeholder: stakeholder/index.md
  - As a Candidate: candidate/index.md

markdown_extensions:
  - footnotes
