site_name: A Considered Approach to Technical Interviews
repo_url: https://github.com/class-act-org/flip-the-interview/
site_url: https://class-act-org.github.io/flip-the-interview/
theme:
  name: null
  custom_dir: "cinder"

  features:
    - content.footnote.tooltips

nav:
  - As a Stakeholder: interviewer.md
  - As a Candidate: interviewee.md

markdown_extensions:
  - footnotes
